const EVENTS = [
    {
        id: "1",
        title: "ROBO SAGA",
        open:"yes",
        description: "Something exciting is on the way. Stay tuned!",
        fullDescription: "The thrilling era today is witnessing rapid metamorphosis in which maniacs can emerge with unsurpassable impetus to spur the development around them. This segment challenges your imagination to realize your dream of bot racing with churning wheels and puffing engine on the terrain you dream of.",
        date: "09/05/2026 - 10/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/RovjumI?lb=1PLt4xRq&utm_medium=Share&utm_source=events&utm_campaign=Harshkum3077",
        image: "./assets/robosaga.png"
    },
    {
        id: "2",
        title: "AQUA ARENA",
        open:"yes",
        description: "Something exciting is on the way. Stay tuned!",
        fullDescription: "Aqua Arena is an exciting water-based robotic competition designed to test participants’ engineering skills, strategic thinking, and precision control. Teams will navigate their boats through a water track, complete interactive tasks, and overcome challenging obstacles.",
        date: "09/05/2026 - 10/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/7VH6L5a?lb=jm3QThrb&utm_medium=Share&utm_source=competitions&utm_campaign=Garvaraj51344",
        image: "./assets/aquarena.png"
    },
    {
        id: "3",
        title: "Drone-A-Thon",
        open:"yes",
        fullDescription: "The main motive of the event is to create a robust, economical, and user-friendly drone that could fit into our daily lives. The event would take place in three stages. The winner will be decided based on the stability, time of flight, and range of the drones.",
        date: "09/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/cVb8xvF?lb=jm3QThrb&utm_medium=Share&utm_source=competitions&utm_campaign=Garvaraj51344",
        image: "./assets/dronathon.png",
    },
    {
        id: "4",
        title: "Pixel Play",
        open:"yes",
        fullDescription: "Pixel Play is a two-round UI/UX design competition designed to evaluate participants’ theoretical knowledge and practical design skills. The event focuses on creativity, usability, and the effective application of UI/UX principles.",
        date: "04/05/2026",
        location: "Unstop (online)",
        wlink:"https://unstop.com/o/woL3sYx?lb=jm3QThrb&utm_medium=Share&utm_source=competitions&utm_campaign=Garvaraj51344",
        image: "./assets/pixelplay.png",
    },
    {
        id: "5",
        title: "AlgoArena",
        open:"yes",
        fullDescription: "AlgoArena is a coding challenge designed to assess participants' fundamental problem-solving skills and coding accuracy. The contest focuses on building strong logical thinking through a set of well-curated questions, encouraging participants to write efficient and correct solutions.",
        date: "08/05/2026",
        location: "GeeksforGeeks (online)",
        wlink:"https://shorturl.at/k2r3a",
        image: "./assets/algoarena.png",
    },
    {
        id: "6",
        title: "HydroFlight",
        open:"yes",
        fullDescription: "Welcome to an exciting competition centered around the fascinating concept of water-pressure propulsion. Participants will showcase their creativity and engineering skills by designing, building, and launching their own water rockets. This challenge goes beyond just racing; it evaluates your understanding of aerodynamics, propulsion mechanics, and energy efficiency while pushing you to innovate and perform under real conditions.",
        date: "09/05/2026-10/05/2026",
        location: "BIT Sindri",
        wlink:"https://shorturl.at/nOJrO",
        image: "./assets/hydroflight.png",
    },
    {
        id: "7",
        title: "Build For BIT",
        open:"yes",
        fullDescription: "Build for BIT is an innovation-driven problem-solving competition where participants design and develop solutions for real-world challenges faced by students. The event focuses on creativity, practical thinking, and technical execution, encouraging participants to build solutions that can create meaningful impact within campus life. ",
        date: "09/05/2026-10/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/WAY15Lp?lb=jm3QThrb&utm_medium=Share&utm_source=competitions&utm_campaign=Garvaraj51344",
        image: "./assets/buildforbit.png",
    },
    {
        id: "8",
        title: "Modex",
        open:"yes",
        fullDescription: "Modex is a technical model exhibition that provides a platform for college students to showcase their innovative ideas, technical knowledge, and creativity through working or conceptual models. The event focuses on encouraging hands-on learning and practical application of theoretical concepts across various engineering and technology domains. ",
        date: "09/05/2026-10/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/fC9J5yj?lb=jm3QThrb&utm_medium=Share&utm_source=events&utm_campaign=Garvaraj51344",
        image: "./assets/modex.png",
    },
    {
        id: "9",
        title: "Prompt Craft",
        open:"yes",
        fullDescription: "Prompt Craft is a multi-round competition where participants must recreate and build digital content (image and website using AI tools. Each team is given a fixed total of only 4/6 prompts for the entire event, which they can use at any stage based on their strategy. This introduces a unique challenge of resource management combined with creativity.",
        date: "09/05/2026",
        location: "BIT Sindri",
        wlink:"https://unstop.com/o/Soiyl4e?lb=jm3QThrb&utm_medium=Share&utm_source=competitions&utm_campaign=Garvaraj51344",
        image: "./assets/promptcraft.png",
    },
    {
        id: "10",
        title: "Shoot At Sight 3.0",
        open:"yes",
        fullDescription: "Do you see yourself as a visionary storyteller or an aspiring director? Shoot at Sight at SANDHAAN’26 is your opportunity to prove it. Create your own short film and showcase it on the big screen, where a live audience will experience and celebrate your creativity.The participants will have to upload the video on Unstop or the Google Form within 2 days of the event. ",
        date: "09/05/2026",
        location: "Unstop(online)",
        wlink:"https://unstop.com/o/dnFSIfv?lb=jm3QThrb&utm_medium=Share&utm_source=events&utm_campaign=Garvaraj51344",
        image: "./assets/shootatsight.png",
    }


    //event sample
    // {
    //     id: "5",
    //     title: "Oscorp Chemistry Lab",
    //     description: "A high-stakes chemistry competition. Don't turn into a lizard!",
    //     fullDescription: "Step into the world of advanced biochemistry at the Oscorp Chemistry Lab. This competition challenges your knowledge of molecular structures and chemical reactions. Solve complex puzzles and perform safe but spectacular experiments. Remember: safety first, and try not to accidentally create any cross-species mutations.",
    //     date: "April 16, 2026",
    //     category: "Science",
    //     image: "https://picsum.photos/seed/chemistry/800/600",
    //     schedule: ["09:30 AM - Lab Safety Briefing", "10:30 AM - Round 1: Theory", "01:30 PM - Round 2: Practical", "04:00 PM - Results"]
    // }
];

